"""add conversation session and messages

Revision ID: 26327f8757cd
Revises: 77ade9ffffa8
Create Date: 2026-09-06 19:28:14.657106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '26327f8757cd'
down_revision: Union[str, Sequence[str], None] = '77ade9ffffa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_consents_patient_id'), 'consents', ['patient_id'], unique=False)
    op.add_column('conversations', sa.Column('session_id', sa.Integer(), nullable=True))
    op.add_column('conversations', sa.Column('messages', sa.JSON(), nullable=False))
    op.create_index(op.f('ix_conversations_patient_id'), 'conversations', ['patient_id'], unique=False)
    op.create_index(op.f('ix_conversations_session_id'), 'conversations', ['session_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'sessions', ['session_id'], ['id'])
    op.drop_constraint(op.f('sessions_session_token_key'), 'sessions', type_='unique')
    op.create_index(op.f('ix_sessions_patient_id'), 'sessions', ['patient_id'], unique=False)
    op.create_index(op.f('ix_sessions_session_token'), 'sessions', ['session_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_session_token'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_patient_id'), table_name='sessions')
    op.create_unique_constraint(op.f('sessions_session_token_key'), 'sessions', ['session_token'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_session_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_patient_id'), table_name='conversations')
    op.drop_column('conversations', 'messages')
    op.drop_column('conversations', 'session_id')
    op.drop_index(op.f('ix_consents_patient_id'), table_name='consents')
    # ### end Alembic commands ###
