"""update medical history

Revision ID: ab2535a32539
Revises: 26327f8757cd
Create Date: 2026-09-06 19:44:56.755050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab2535a32539'
down_revision: Union[str, Sequence[str], None] = '26327f8757cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_medical_histories_conversation_id'), 'medical_histories', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_medical_histories_patient_id'), 'medical_histories', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medical_histories_patient_id'), table_name='medical_histories')
    op.drop_index(op.f('ix_medical_histories_conversation_id'), table_name='medical_histories')
    # ### end Alembic commands ###
