"""enhance lab reports and medications

Revision ID: b2254065ed11
Revises: ab2535a32539
Create Date: 2026-09-06 21:48:53.877055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2254065ed11'
down_revision: Union[str, Sequence[str], None] = 'ab2535a32539'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_reports', sa.Column('report_date', sa.Date(), nullable=True))
    op.add_column('lab_reports', sa.Column('status', sa.String(length=50), nullable=False))
    op.alter_column('lab_reports', 'result',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.create_index(op.f('ix_lab_reports_document_id'), 'lab_reports', ['document_id'], unique=False)
    op.create_index(op.f('ix_lab_reports_patient_id'), 'lab_reports', ['patient_id'], unique=False)
    op.add_column('medications', sa.Column('route', sa.String(length=100), nullable=True))
    op.add_column('medications', sa.Column('start_date', sa.Date(), nullable=True))
    op.add_column('medications', sa.Column('end_date', sa.Date(), nullable=True))
    op.add_column('medications', sa.Column('status', sa.String(length=50), nullable=False))
    op.create_index(op.f('ix_medications_patient_id'), 'medications', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_medications_patient_id'), table_name='medications')
    op.drop_column('medications', 'status')
    op.drop_column('medications', 'end_date')
    op.drop_column('medications', 'start_date')
    op.drop_column('medications', 'route')
    op.drop_index(op.f('ix_lab_reports_patient_id'), table_name='lab_reports')
    op.drop_index(op.f('ix_lab_reports_document_id'), table_name='lab_reports')
    op.alter_column('lab_reports', 'result',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.drop_column('lab_reports', 'status')
    op.drop_column('lab_reports', 'report_date')
    # ### end Alembic commands ###
