"""enforce one patient and physician profile per user

Revision ID: f8eb59352664
Revises: 9bd22bc86a60
Create Date: 2026-09-09 01:30:48.228330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8eb59352664'
down_revision: Union[str, Sequence[str], None] = '9bd22bc86a60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'patients', ['user_id'])
    op.create_unique_constraint(None, 'physicians', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'physicians', type_='unique')
    op.drop_constraint(None, 'patients', type_='unique')
    # ### end Alembic commands ###
